### ISSUE TITLE
[TO-DO] Your Regular TODO issue placeholder

### ISSUE THREAD

**Issue by raphielscape** [MyPaperPlane/Telegram-UserBot#151]
### The To-Do's for now

- [x] Global Ban / Federation Ban Reworks
- [ ] Integrate Kantek

**Comment by baalajimaestro** [comment]
* [ ] Integrate Kantek

**Comment by zakaryan2004** [comment]
- [ ]  A new implementation of Google Search

**Comment by AvinashReddy3108** [comment]
>     * [ ]   A new implementation of Google Search

PR coming in hot !!
